config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular', to: 'portfolios#angular'

  get 'pages/home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
# frozen_string_literal: true

##
# model for /blogs
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }

  extend FriendlyId

  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
# frozen_string_literal: true

##
# Manages all the placeholders (default values) for models
module Placeholder
  extend ActiveSupport::Concern

  def self.generate_image(height:, width:)
    "https://dummyimage.com/#{height}x#{width}/fff/aaa"
  end
end

app/models/portfolio.rb
# frozen_string_literal: true

class Portfolio < ApplicationRecord
  include Placeholder

  validates_presence_of :title, :body, :main_image, :thumb_image
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: ->(attrs) { attrs['name'].blank? }

  scope :angular, -> { where subtitle: 'Angular' }

  def self.rails
    where(subtitle: 'Ruby on Rails')
  end

  after_initialize :set_defaults

  def set_defaults
    self.main_image  ||= Placeholder.generate_image(width: 600, height: 400)
    self.thumb_image ||= Placeholder.generate_image(width: 350, height: 200)
  end
end

app/models/skill.rb
# frozen_string_literal: true

##
# Skill
class Skill < ApplicationRecord
  include Placeholder

  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.generate_image(height: 250, width: 250)
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    name.split.first
  end

  def last_name
    name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

##
# Regulates actions for route /blogs
#
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        forma.html { redirect_to blog_url(@blog), notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/concerns/devise_whitelist.rb
# frozen_string_literal: true

j#
# Signing in/out config
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @pages = Blog.all
    @skills = Skill.all
  end

  def about; end

  def contact; end
end

app/controllers/portfolios_controller.rb
# frozen_string_literal: true

##
# DB entry point for Portfolios
class PortfoliosController < ApplicationController
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new

    3.times { @portfolio_item.technologies.build }
  end

  def create
    # puts "Params[portfolio]: #{params[:portfolio]}"
    @portfolio_item = Portfolio.new(
      params[:portfolio]
      .permit(:title, :subtitle, :body, technologies_attribute: [:name])
    )

    if @portfolio_item.save
      redirect_to portfolios_path, notice: 'Portfolio successfully created'
    else
      render 'new', notice: 'Something went wrong'
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy

    respond_to do |format|
      format.html do
        redirect_to portfolios_path,
                    notice: 'Record was successfully destroyed.'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>
</div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog)%></td>
        <td><%= link_to 'Delete', blog, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.any? %>
      <%= flash.to_hash.values.join("\n") %>
    <% end %>

    <br/>
    <% if current_user %>
      <%# rel: "nofollow" to prevent browser from following the link %>
      <%= link_to 'logout', destroy_user_session_path, rel: "nofollow", data: { turbo_method: 'delete' } %>
    <% else %>
      <%= link_to 'login', new_user_session_path %>
      <%= link_to 'register', new_user_registration_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1><%="Hi, " + current_user.first_name if current_user %></h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1>Blog posts</h1>
<table>
  <tbody>
    <% @pages.each do |page| %>
      <td><%= page.title %></td>
    <% end %>
  </tbody>
</table>
<h1>Skills</h1>
<% @skills.each do |skill| %>
  <p><%= skill.title %>: <%=skill.percent_utilized %> percents</p>
<% end %>

app/views/portfolios/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to 'Create New Item', new_portfolio_path %>
<div>
  <% @angular.each do |item| %>
    <h2> <%= link_to item.title, portfolio_show_path(item) %> </h2>
    <h3> <%= item.subtitle %> </h3>
    <h3>Body:</h3>
    <p> <%= item.body %> </p>
    <p> <%= image_tag item.thumb_image unless item.thumb_image.nil? %> </p>
    <p> <%= link_to "Edit", edit_portfolio_path(item) %> </p>
    <p> <%= link_to "Delete", portfolio_path(item), data: { turbo_confirm: "Are you sure?", turbo_method: "delete" } %> </p>
  <% end %>
</div>

app/views/portfolios/edit.html.erb
<h1>Edit the Portfolio item</h1>

<%= form_with(model: @portfolio_item) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to 'Create New Item', new_portfolio_path %>
<div>
  <% @portfolio_items.each do |item| %>
    <h2> <%= link_to item.title, portfolio_show_path(item) %> </h2>
    <h3> <%= item.subtitle %> </h3>
    <h3>Body:</h3>
    <p> <%= item.body %> </p>
    <p> <%= image_tag item.thumb_image unless item.thumb_image.nil? %> </p>
    <p> <%= link_to "Edit", edit_portfolio_path(item) %> </p>
    <p> <%= link_to "Delete", portfolio_path(item), data: { turbo_confirm: "Are you sure?", turbo_method: "delete" } %> </p>
  <% end %>
</div>

app/views/portfolios/new.html.erb
<h1>New Portfolio item</h1>

<%= form_with(model: @portfolio_item) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |tech_form| %>
      <li>
        <%= tech_form.label :name %>
        <%= tech_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<% @portfolio_item.technologies.each do |tech| %>
  <p><%= tech.name %></p>
<% end %>

<%= link_to 'Main Portfolio Page', portfolios_path %>